name: trigger jenkins job
on: [push]

# on:
    # pull_request_target:
    #   types: [closed]

jobs:
    build:
        # if: (github.event.pull_request.merged == true) && !(startsWith(github.head_ref, 'auto-pr/'))
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: trigger single Job
          uses: appleboy/jenkins-action@master
          with:
            url: "https://node-build.e2ro.com"
            user: "eder.beserra"
            token: ${{ secrets.TOKEN }}
            job: "recipe_branch_test"
            parameters: 