name: trigger jenkins job
on:
  push:
    branches:
      - 'main'
  
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Avro Docs
        env:
          BOT_USER: ${{ github.actor }}
          BOT_USER_ID: ${{ github.actor_id }}
        run: |
          # create avrodocs folder
          mkdir -p avrodocs
          npx @mikaello/avrodoc-plus -i events -o avrodocs/index.html
          git config user.email "$BOT_USER_ID+$BOT_USER@users.noreply.github.com"
          git config user.name "$BOT_USER"
          git add avrodocs
          git commit -m "Generating Avro docs from changes by $BOT_USER"
          git push