name: trigger jenkins job
on:
  push:
    branches:
      - 'main'
  
  workflow_dispatch:

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Avro Docs
        env:
          BOT_USER: ${{ github.actor }}
          BOT_USER_ID: ${{ github.actor_id }}
        shell: bash {0}
        run: |
          git config --global url.https://x-access-token:$GH_TOKEN@github.com/.insteadOf https://github.com/
          git config user.email "$BOT_USER_ID+$BOT_USER@users.noreply.github.com"
          git config user.name "$BOT_USER"
          git fetch
          # create avrodocs folder
          mkdir -p avrodocs
          npx @mikaello/avrodoc-plus -i events -o avrodocs/index.html --title "eero Event Schema Docs"
          git add avrodocs
          git commit -m "Generating Avro docs from changes by $BOT_USER"
          git checkout docs
          git cherry-pick main
          if [ $? -ne 0 ]; then
            git checkout --theirs avrodocs
            git add avrodocs
            (git commit -m "Generating Avro docs from changes by $BOT_USER" || true)
          fi
          git push
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only the Avro docs folder
          path: 'avrodocs/'
          branch: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4